# Kubernetes Version
k8s_version: stable-1


#### CIDRs ####
## Service CIDR
# It is for kubeadm init option --service-cidr
service_cidr: "10.96.0.0/12"
#
## POD Network CIDR 
# Specify range of IP addresses for the pod network
# It is for kubeadm init option --pod-network-cidr
pod_network_cidr: "10.240.0.0/16"


#### KubeAPI Port ####
# Port Number for kubernetes KubeAPI Server
kubeapi_port: 6443


#### Other Init Options ####
# Any other additional options to add in init subcommand of kubeadm
# See all Init options here - https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
#
# If your system/instance have <2 CPU and <1700MB RAM then pass --ignore-preflight-errors="NumCPU,Mem" to init_opts
#
## Note - Don't pass options --kubernetes-version, --apiserver-bind-port, --service-cidr and --pod-network-cidr here 
## as they are already passed using above variables
#
## For example :-
#  kubeadm_opts: '--token ab34ef.0123456789abcdef --skip-token-print --ignore-preflight-errors="NumCPU,Mem"'
init_opts: ''


#### Other Kubeadm Options ####
# Any other additional options to add in kubeadm command
#
## For example :-
#  kubeadm_opts: '--add-dir-header --log-file /file/path'
kubeadm_opts: ''
